<?php
?>
<?php if ($this->canViewToolbar()): ?>
    <?php if (Mage::app()->getStore()->isAdmin()): ?>
        <script type="text/javascript">
        //<![CDATA[
        Mage.Cookies.path     = '<?php echo $this->getPath()?>';
        Mage.Cookies.domain   = '<?php echo $this->getDomain()?>';
        //]]>
        </script>
    <?php endif ?>

    <div class="weeDeveloperToolbar" id="weeDeveloperToolbarContainer">
      <img class="magentoLogo" src="<?php echo $this->getSkinUrl('images/wee_developertoolbar/logo.png'); ?>" alt="" />
        <?php if ($this->getItems()): ?>
        <ul id="weeDeveloperToolbar">
            <?php foreach ($this->getItems() as $item): ?>
              <?php echo $item->render(); ?>
            <?php endforeach ?>
        </ul>
        <?php endif ?>
    </div>

    <?php foreach ($this->getItems() as $item): ?>
      <?php if ($item->getContent()): ?>
        <div class="weeDeveloperToolbarDetails" id="weeDeveloperToolbarDetails_<?php echo $item->getName(); ?>" style="display:none;">
          <?php echo $item->renderContent(); ?>
        </div>
      <?php endif ?>
    <?php endforeach ?>
<?php endif;?>