<?php
$traces = $this->getSuspectedCalls();
$i = 0;
?>
<form action="" method="post">
<input type="text" class="developerToolbar"  id="trace_part" name="trace_part" value="<?php echo Mage::getSingleton('mrsgto_checkup/session')->getTraceSqlPart() ? Mage::getSingleton('mrsgto_checkup/session')->getTraceSqlPart() : ''; ?>" />
<input type="button" class="developerToolbar" onClick="setTracePart()" name="submit"  value="<?php echo $this->__('Update'); ?>">
</form>
<span id="trace-part-result"></span>
<script type="text/javascript">
setTracePart = function() {
  new Ajax.Updater('trace-part-result', '<?php echo Mage::getUrl('mrsgto_checkup/index/tracePart'); ?>', {
      parameters: { part: $('trace_part').value }
  });
}
</script>
<table class="stripped" border="0" cellpadding="0" cellspacing="0" style="width:100%">
  <tr>
    <th>Code Pool</th>
    <th>Vendor</th>
    <th>Module</th>
    <th>Class Path</th>
    <th>Call in</th>
    <th>Line&nbsp;</th>
    <th>Stacks&nbsp;</th>
    <th>Queries&nbsp;</th>
    <th style="width:40px">&nbsp;</th>
    <th style="width:40px">&nbsp;</th>
    <th style="width:40px">&nbsp;</th>
  </tr>
<?php foreach ($traces as $trace):?>
  <tr class="<?php echo ($i % 2 ? 'even' : 'odd'); ?>">
    <td><?php echo $trace['code_pool']; ?></td>
    <td><?php echo $trace['module_vendor']; ?></td>
    <td><?php echo $trace['module_name']; ?></td>
    <td><?php echo $trace['class_path']; ?></td>
    <td><?php echo $trace['class_method']; ?></td>
    <td><?php echo $trace['class_line']; ?></td>
    <td><?php echo count($trace['stack_call']); ?></td>
    <td><?php echo $trace['number']; ?></td>
    <td>
        <button class="developerToolbar" onclick="javascript:getSimpleBackTrace(<?php echo $i; ?>);return false;" id="template_button_<?php echo $i; ?>" type="button">Backtrace</button>
    </td>
    <td>
    <?php if(!empty($trace['template_path'])):?>
    <button class="developerToolbar" onclick="javascript:getTemplateTrace(<?php echo $i; ?>);return false;" id="template_button_<?php echo $i; ?>" type="button">Template</button>
    <?php endif;?>
    </td>
    <td>
        <button class="developerToolbar" onclick="javascript:getQuery(<?php echo $i; ?>);return false;" id="template_button_<?php echo $i; ?>" type="button">Query</button>
    </td>

  </tr>

  <?php if(!empty($trace['simple_traces'])):?>
    <?php foreach ($trace['simple_traces'] as $simpletrace=>$traceInfo):?>
      <tr class="<?php echo ($i % 2 ? 'even' : 'odd'); ?> simple_traces_<?php echo $i; ?>" style="display:none">
        <td>&nbsp;:Backtrace:</td>
        <td colspan="4"><i><?php echo $simpletrace; ?></i></td>
        <td colspan="2"></td>
        <td><?php echo $traceInfo;?></td>
        <td colspan="3"></td>
      </tr>
    <?php endforeach;?>
  <?php endif;?>

  <?php if(!empty($trace['template_path'])):?>
    <?php foreach ($trace['template_path'] as $templateInfo):?>
      <tr class="<?php echo ($i % 2 ? 'even' : 'odd'); ?> template_detail_<?php echo $i; ?>" style="display:none">
        <td>&nbsp;:Template:</td>
        <td colspan="2"><i><?php echo $templateInfo['template']; ?></i></td>
        <td colspan="2"><?php echo $templateInfo['call']; ?></td>
        <td><?php echo $templateInfo['line']; ?></td>
        <td></td>
        <td><?php echo $templateInfo['number']; ?></td>
        <td colspan="3"></td>
      </tr>
    <?php endforeach;?>
  <?php endif;?>

  <?php if(!empty($trace['sql_query'])):?>
      <?php foreach ($trace['sql_query'] as $query):?>
          <tr class="<?php echo ($i % 2 ? 'even' : 'odd'); ?> sql_query_<?php echo $i; ?>" style="display:none">
            <td>&nbsp;:Query:</td>
            <td colspan="7"><i><?php echo $query; ?></i></td>
            <td colspan="3"></td>
          </tr>
      <?php endforeach;?>
  <?php endif;?>
<?php $i++; ?>
<?php endforeach;?>
</table>
<script type="text/javascript">
<!--
getTemplateTrace = function(i)
{
    $$('tr.template_detail_'+i).each(function(line){
        line.toggle();
    });
}


getSimpleBackTrace = function(i)
{
    $$('tr.simple_traces_'+i).each(function(line){
        line.toggle();
    });
}

getQuery = function(i)
{
    $$('tr.sql_query_'+i).each(function(line){
        line.toggle();
    });
}
//-->
</script>