<?php
$traces = $this->getStatisticsCalls();
$i = 0;
?>
<table class="stripped" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <th>Code Pool</th>
    <th>Vendor</th>
    <th>Module</th>
    <th>Time</th>
    <th>Query Nbr</th>
  </tr>
<?php foreach ($traces as $trace):?>
  <tr class="<?php echo ($i % 2 ? 'even' : 'odd'); ?>">
    <td><?php echo $trace['code_pool']; ?></td>
    <td><?php echo $trace['module_vendor']; ?></td>
    <td><?php echo $trace['module_name']; ?></td>
    <td><?php echo $trace['elapsed_time']; ?></td>
    <td><?php echo $trace['number']; ?></td>
  </tr>
<?php $i++; ?>
<?php endforeach;?>
</table>