<?php
$_timers = $this->getTimers();
$i = 0;
?>
<table class="profilerTable stripped sortable" border="0" cellpadding="0" cellspacing="0">
    <thead>
      <tr class="head">
        <th><?php echo $this->__('Name'); ?></th>
        <th><?php echo $this->__('Time'); ?></th>
        <th><?php echo $this->__('Cnt'); ?></th>
        <th><?php echo $this->__('Emalloc'); ?></th>
        <th><?php echo $this->__('RealMem'); ?></th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($_timers as $timerName => $timerData): ?>
          <tr class="<?php echo ($i % 2 ? 'even' : 'odd'); ?>">
            <td><?php echo $timerName; ?></td>
            <td><?php echo number_format($timerData['sum'],6); ?></td>
            <td><?php echo $timerData['count']; ?></td>
            <td><?php echo number_format($timerData['emalloc']); ?></td>
            <td><?php echo Mage::helper('wee_developertoolbar')->formatBytes($timerData['emalloc']); ?></td>
          </tr>
        <?php $i++; ?>
      <?php endforeach ?>
    </tbody>
</table>
