<?php
$_helper = Mage::helper('wee_developertoolbar');
$_profiler = $this->getProfiler();
$_queries = $_profiler->getQueryProfiles();
?>
<?php if ($_queries): ?>
<table class="stripped" border="0" cellpadding="0" cellspacing="0">
   <tr>
    <td>
      <strong><?php echo $this->__('Executed:'); ?></strong>
    </td>
    <td>
      <?php echo sprintf('%s queries in %s', $_profiler->getTotalNumQueries(), $_helper->formatSqlTime($_profiler->getTotalElapsedSecs())); ?>
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Type:'); ?></strong>
    </td>
    <td>
      <?php echo sprintf('%s SELECT - %s INSERT - %s UPDATE - %s DELETE - %s TRANSACTION',
              $this->getProfiler()->getTotalNumQueries(Zend_Db_Profiler::SELECT),
              $this->getProfiler()->getTotalNumQueries(Zend_Db_Profiler::INSERT),
              $this->getProfiler()->getTotalNumQueries(Zend_Db_Profiler::UPDATE),
              $this->getProfiler()->getTotalNumQueries(Zend_Db_Profiler::DELETE),
              $this->getProfiler()->getTotalNumQueries(Zend_Db_Profiler::TRANSACTION)); ?>
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Average:'); ?></strong>
    </td>
    <td>
      <?php echo $_helper->formatSqlTime($_profiler->getTotalNumQueries() &&  $_profiler->getTotalElapsedSecs() ? $_profiler->getTotalElapsedSecs()/$_profiler->getTotalNumQueries() : 0); ?>
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Queries/second:'); ?></strong>
    </td>
    <td>
      <?php echo ($_profiler->getTotalNumQueries() && $_profiler->getTotalElapsedSecs() ?  $_profiler->getTotalNumQueries()/$_profiler->getTotalElapsedSecs() : 0); ?>
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Longest:'); ?></strong>
    </td>
    <td>
      <?php echo $_helper->formatSqlTime($this->getLongestQueryTime()); ?>
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Longest:'); ?></strong>
    </td>
    <td>
      <?php echo $_helper->formatSql(wordwrap($this->getLongestQuery())); ?>
    </td>
  </tr>

</table>

<table class="stripped" >
    <tr>
        <th>#</th>
        <th>Sql</th>
        <th><?php echo $this->__('Elapsed'); ?></th>
    </tr>
<thead>
</thead>
<tbody>
<?php
  $i = 0;
  foreach ($_queries as $query): ?>
    <tr class="<?php echo ($i % 2 ? 'even' : 'odd')?>">
      <td><?php echo $i;?></td>
      <td>
          <?php echo $_helper->formatSql(wordwrap($query->getQuery())); ?>
      </td>
      <td>
          <span class="queryInfo">
           <?php echo $_helper->formatSqlTime($query->getElapsedSecs()) ?>
          </span>
      </td>
    </tr>
    <?php $i++; ?>
  <?php endforeach ?>
</tbody>
</table>
<?php  endif ?>